DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS card_tags;
DROP TABLE IF EXISTS deck_tags;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS decks;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
